export declare const Card: string
export declare const CardContent: string
export declare const CardTitle: string
export declare const Carousel: string
export declare const Description: string
export declare const Dot: string
export declare const ExperienceItem: string
export declare const ExperienceList: string
export declare const Scrolling: string
export declare const ScrollingReverse: string
export declare const Slider: string
export declare const SliderReverse: string
export declare const Timeline: string
export declare const TimelineContent: string
export declare const TimelineDate: string
export declare const TimelineDescription: string
export declare const TimelineItem: string
export declare const TimelineMarker: string
